# Generated by Django 4.2.10 on 2026-03-10 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_merge_0004_passwordresettoken_and_more_0005_userpref'),
        ('organizations', '0001_initial'),
        ('controls', '0006_remove_appliedcontrol_idx_applied_maturity_status_and_more'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_percentage', models.DecimalField(decimal_places=2, help_text='Overall compliance coverage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('compliance_score', models.DecimalField(decimal_places=2, help_text='Weighted compliance score based on control effectiveness (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_requirements', models.IntegerField(default=0, help_text='Total requirements in framework')),
                ('requirements_addressed', models.IntegerField(default=0, help_text='Requirements with at least one control')),
                ('requirements_compliant', models.IntegerField(default=0, help_text='Requirements fully compliant')),
                ('requirements_partial', models.IntegerField(default=0, help_text='Requirements partially compliant')),
                ('requirements_non_compliant', models.IntegerField(default=0, help_text='Requirements not compliant')),
                ('controls_with_evidence', models.IntegerField(default=0, help_text='Controls with at least one evidence')),
                ('total_evidence_count', models.IntegerField(default=0, help_text='Total evidence items linked')),
                ('high_risk_gaps', models.IntegerField(default=0, help_text='Number of high-risk compliance gaps')),
                ('medium_risk_gaps', models.IntegerField(default=0, help_text='Number of medium-risk compliance gaps')),
                ('low_risk_gaps', models.IntegerField(default=0, help_text='Number of low-risk compliance gaps')),
                ('requirement_details', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown by requirement')),
                ('control_details', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown by control')),
                ('calculation_date', models.DateTimeField(auto_now_add=True, help_text='When this result was calculated')),
                ('total_controls', models.IntegerField(default=0)),
                ('controls_operational', models.IntegerField(default=0)),
                ('controls_implemented', models.IntegerField(default=0, help_text='Number of controls in implemented status')),
                ('controls_in_progress', models.IntegerField(default=0, help_text='Number of controls currently in progress')),
                ('controls_not_started', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('calculating', 'Calculating'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Whether this is the current/latest result')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_compliance_results', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('department', models.ForeignKey(blank=True, help_text='Optional department scope (null = company-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='organizations.department')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='library.framework')),
            ],
            options={
                'db_table': 'compliance_results',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('summary', 'Executive Summary'), ('detailed', 'Detailed Assessment'), ('gap_analysis', 'Gap Analysis'), ('evidence_matrix', 'Evidence Matrix'), ('control_matrix', 'Control Matrix'), ('audit_report', 'Audit Report')], default='summary', max_length=50)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='compliance_reports/%Y/%m/')),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=20)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='organizations.department')),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='library.framework')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceGap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gap_type', models.CharField(choices=[('missing_control', 'Missing Control'), ('incomplete_implementation', 'Incomplete Implementation'), ('insufficient_evidence', 'Insufficient Evidence'), ('control_ineffective', 'Control Ineffective'), ('outdated_evidence', 'Outdated Evidence')], default='missing_control', max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('description', models.TextField(help_text='Detailed gap description')),
                ('remediation_plan', models.TextField(blank=True)),
                ('remediation_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('accepted', 'Risk Accepted')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('affected_controls', models.ManyToManyField(blank=True, related_name='compliance_gaps', to='controls.appliedcontrol')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('compliance_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='compliance.complianceresult')),
                ('remediation_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_assignments', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_gaps', to='library.requirement')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_gaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkAdoption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adoption_status', models.CharField(choices=[('planning', 'Planning'), ('implementing', 'Implementing'), ('operational', 'Operational'), ('certified', 'Certified'), ('suspended', 'Suspended')], db_index=True, default='planning', max_length=30)),
                ('target_completion_date', models.DateField(blank=True, help_text='Target date for full compliance', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='Actual date achieved', null=True)),
                ('is_certified', models.BooleanField(default=False, help_text='Whether company is officially certified')),
                ('certification_body', models.CharField(blank=True, help_text='Certification authority', max_length=255)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('certification_expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=255)),
                ('scope_description', models.TextField(blank=True, help_text='What is included in the scope')),
                ('scope_exclusions', models.TextField(blank=True, help_text='What is excluded from scope')),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('next_audit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='library.framework')),
                ('program_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_framework_adoptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'framework_adoptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'adoption_status'], name='framework_a_company_79ece8_idx'), models.Index(fields=['company', 'is_certified'], name='framework_a_company_a3ad6b_idx'), models.Index(fields=['certification_expiry_date'], name='framework_a_certifi_67865d_idx')],
                'unique_together': {('company', 'framework')},
            },
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['company', 'framework', '-calculation_date'], name='compliance__company_d9863b_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['company', 'department', '-calculation_date'], name='compliance__company_ac807a_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['company', 'is_current'], name='compliance__company_e9667f_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['framework', 'is_current'], name='compliance__framewo_e063b7_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['company', 'framework', '-created_at'], name='compliance__company_fe2ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['company', 'generation_status'], name='compliance__company_820c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancegap',
            index=models.Index(fields=['company', 'status'], name='compliance__company_0dbf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancegap',
            index=models.Index(fields=['compliance_result', 'severity'], name='compliance__complia_8f90a2_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancegap',
            index=models.Index(fields=['remediation_due_date'], name='compliance__remedia_5bcd1b_idx'),
        ),
    ]
