# Generated by Django 4.2.10 on 2026-02-16 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('controls', '0002_initial'),
        ('compliance', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceresult',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional department scope (null = company-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='complianceresult',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_results', to='library.framework'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='library.framework'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancegap',
            name='affected_controls',
            field=models.ManyToManyField(blank=True, related_name='compliance_gaps', to='controls.appliedcontrol'),
        ),
        migrations.AddField(
            model_name='compliancegap',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='compliancegap',
            name='compliance_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='compliance.complianceresult'),
        ),
        migrations.AddField(
            model_name='compliancegap',
            name='remediation_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancegap',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_gaps', to='library.requirement'),
        ),
        migrations.AddField(
            model_name='compliancegap',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_gaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='frameworkadoption',
            index=models.Index(fields=['company', 'adoption_status'], name='framework_a_company_79ece8_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkadoption',
            index=models.Index(fields=['company', 'is_certified'], name='framework_a_company_a3ad6b_idx'),
        ),
        migrations.AddIndex(
            model_name='frameworkadoption',
            index=models.Index(fields=['certification_expiry_date'], name='framework_a_certifi_67865d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='frameworkadoption',
            unique_together={('company', 'framework')},
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['company', 'framework', '-calculation_date'], name='compliance__company_d9863b_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['company', 'department', '-calculation_date'], name='compliance__company_ac807a_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['company', 'is_current'], name='compliance__company_e9667f_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceresult',
            index=models.Index(fields=['framework', 'is_current'], name='compliance__framewo_e063b7_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['company', 'framework', '-created_at'], name='compliance__company_fe2ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['company', 'generation_status'], name='compliance__company_820c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancegap',
            index=models.Index(fields=['company', 'status'], name='compliance__company_0dbf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancegap',
            index=models.Index(fields=['compliance_result', 'severity'], name='compliance__complia_8f90a2_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancegap',
            index=models.Index(fields=['remediation_due_date'], name='compliance__remedia_5bcd1b_idx'),
        ),
    ]
