# Generated by Django 4.2.10 on 2026-02-16 18:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('controls', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Risk title/name', max_length=500)),
                ('description', models.TextField(help_text='Detailed risk description')),
                ('risk_id', models.CharField(blank=True, help_text='Custom risk identifier (e.g., "R-001")', max_length=50)),
                ('risk_category', models.CharField(choices=[('strategic', 'Strategic Risk'), ('operational', 'Operational Risk'), ('financial', 'Financial Risk'), ('compliance', 'Compliance/Regulatory Risk'), ('reputational', 'Reputational Risk'), ('technology', 'Technology Risk'), ('security', 'Security Risk'), ('environmental', 'Environmental Risk'), ('legal', 'Legal Risk'), ('other', 'Other')], default='operational', max_length=100)),
                ('risk_source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('both', 'Both')], default='internal', max_length=100)),
                ('inherent_likelihood', models.IntegerField(help_text='Likelihood without controls (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('inherent_impact', models.IntegerField(help_text='Impact without controls (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('inherent_risk_score', models.IntegerField(default=0, help_text='Calculated inherent risk score')),
                ('inherent_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('potential_causes', models.TextField(blank=True, help_text='What could cause this risk to materialize')),
                ('potential_consequences', models.TextField(blank=True, help_text='What would happen if this risk occurs')),
                ('treatment_strategy', models.CharField(choices=[('mitigate', 'Mitigate/Reduce'), ('transfer', 'Transfer'), ('accept', 'Accept'), ('avoid', 'Avoid/Eliminate')], default='mitigate', max_length=20)),
                ('treatment_plan', models.TextField(blank=True, help_text='How the risk will be treated')),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('assessing', 'Assessing'), ('treating', 'Treating'), ('monitoring', 'Monitoring'), ('closed', 'Closed')], db_index=True, default='identified', max_length=20)),
                ('target_likelihood', models.IntegerField(blank=True, help_text='Target likelihood after treatment', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('target_impact', models.IntegerField(blank=True, help_text='Target impact after treatment', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('review_frequency_days', models.IntegerField(default=90, help_text='Review frequency in days')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('department', models.ForeignKey(blank=True, help_text='Affected department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='organizations.department')),
            ],
            options={
                'db_table': 'risks',
                'ordering': ['-inherent_risk_score', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Matrix name (e.g., "5x5 Standard Risk Matrix")', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('likelihood_levels', models.IntegerField(default=5, help_text='Number of likelihood levels (3-10)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('impact_levels', models.IntegerField(default=5, help_text='Number of impact levels (3-10)', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('likelihood_definitions', models.JSONField(default=dict, help_text='Likelihood level definitions: {1: {"label": "Rare", "description": "...", "probability": "0-10%"}, ...}')),
                ('impact_definitions', models.JSONField(default=dict, help_text='Impact level definitions: {1: {"label": "Negligible", "description": "...", "financial_impact": "$0-$10k"}, ...}')),
                ('risk_score_matrix', models.JSONField(default=dict, help_text='Risk scores: {"1,1": 1, "1,2": 2, ...} where key is "likelihood,impact"')),
                ('low_risk_threshold', models.IntegerField(default=5, help_text='Scores below this are low risk')),
                ('medium_risk_threshold', models.IntegerField(default=10, help_text='Scores below this are medium risk')),
                ('high_risk_threshold', models.IntegerField(default=15, help_text='Scores below this are high risk (above is critical)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one matrix should be active per company')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
            ],
            options={
                'verbose_name_plural': 'Risk Matrices',
                'db_table': 'risk_matrices',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField(help_text='When the risk event occurred')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(help_text='What happened')),
                ('actual_likelihood', models.IntegerField(help_text='How likely was it (realized as 100%)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('actual_impact', models.IntegerField(help_text='Actual impact level', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('financial_impact', models.DecimalField(blank=True, decimal_places=2, help_text='Actual financial cost', max_digits=15, null=True)),
                ('response_actions', models.TextField(blank=True, help_text='Actions taken in response')),
                ('lessons_learned', models.TextField(blank=True, help_text='What was learned from this event')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='risk.risk')),
            ],
            options={
                'db_table': 'risk_events',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_effectiveness', models.CharField(choices=[('not_effective', 'Not Effective'), ('partially_effective', 'Partially Effective'), ('effective', 'Effective'), ('highly_effective', 'Highly Effective')], default='effective', help_text='How effective is this control at reducing the risk', max_length=20)),
                ('effectiveness_rating', models.IntegerField(default=50, help_text='Effectiveness percentage (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('residual_likelihood', models.IntegerField(help_text='Likelihood after control is applied', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('residual_impact', models.IntegerField(help_text='Impact after control is applied', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('residual_score', models.IntegerField(default=0, help_text='Calculated residual risk score')),
                ('residual_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('assessment_date', models.DateField(help_text='When this assessment was performed')),
                ('assessment_notes', models.TextField(blank=True, help_text='Notes on the assessment')),
                ('is_current', models.BooleanField(db_index=True, default=True, help_text='Whether this is the current assessment')),
                ('applied_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='controls.appliedcontrol')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risk.risk')),
            ],
            options={
                'db_table': 'risk_assessments',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='risk.riskmatrix'),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_owner',
            field=models.ForeignKey(blank=True, help_text='Person accountable for managing this risk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RiskTreatmentAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_title', models.CharField(max_length=500)),
                ('action_description', models.TextField()),
                ('action_type', models.CharField(choices=[('implement_control', 'Implement Control'), ('improve_control', 'Improve Existing Control'), ('transfer_risk', 'Transfer Risk'), ('policy_change', 'Policy Change'), ('training', 'Training/Awareness'), ('technology', 'Technology Implementation'), ('other', 'Other')], default='implement_control', max_length=50)),
                ('due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_notes', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('action_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_actions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_actions', to='risk.risk')),
            ],
            options={
                'db_table': 'risk_treatment_actions',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['company', 'risk'], name='risk_treatm_company_a9762f_idx'), models.Index(fields=['company', 'status'], name='risk_treatm_company_5a6edb_idx'), models.Index(fields=['action_owner', 'status'], name='risk_treatm_action__0ae56f_idx'), models.Index(fields=['due_date'], name='risk_treatm_due_dat_c42675_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='riskmatrix',
            index=models.Index(fields=['company', 'is_active'], name='risk_matric_company_868409_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['company', 'risk'], name='risk_events_company_396162_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['event_date'], name='risk_events_event_d_9aadd5_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['is_resolved'], name='risk_events_is_reso_ae28a2_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['company', 'risk'], name='risk_assess_company_19b92f_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['company', 'applied_control'], name='risk_assess_company_f53051_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['risk', 'is_current'], name='risk_assess_risk_id_43bae0_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['assessment_date'], name='risk_assess_assessm_a99a83_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['company', 'status'], name='risks_company_51c9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['company', 'risk_category'], name='risks_company_d84826_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['company', 'inherent_risk_level'], name='risks_company_216140_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_owner', 'status'], name='risks_risk_ow_2ba7da_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['next_review_date'], name='risks_next_re_214796_idx'),
        ),
    ]
