# Generated by Django 4.2.10 on 2026-03-17 12:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('testing', 'Testing'), ('operational', 'Operational'), ('needs_improvement', 'Needs Improvement'), ('non_compliant', 'Non-Compliant')], db_index=True, default='not_started', max_length=30)),
                ('implementation_notes', models.TextField(blank=True, help_text='Company-specific implementation details')),
                ('custom_procedures', models.TextField(blank=True, help_text='Company-specific procedures')),
                ('custom_frequency', models.CharField(blank=True, help_text='Override default frequency', max_length=50)),
                ('effectiveness_rating', models.IntegerField(blank=True, help_text='1=Ineffective, 5=Highly Effective', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_tested_date', models.DateField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('has_deficiencies', models.BooleanField(default=False)),
                ('deficiency_notes', models.TextField(blank=True)),
                ('remediation_plan', models.TextField(blank=True)),
                ('remediation_due_date', models.DateField(blank=True, null=True)),
                ('implementation_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in company currency', max_digits=12, null=True)),
                ('annual_maintenance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maturity_level', models.IntegerField(choices=[(1, 'Level 1 - Initial/Ad-hoc'), (2, 'Level 2 - Managed'), (3, 'Level 3 - Defined'), (4, 'Level 4 - Quantitatively Managed'), (5, 'Level 5 - Optimizing')], db_index=True, default=1)),
                ('maturity_target_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3)),
                ('maturity_assessment_date', models.DateField(blank=True, null=True)),
                ('maturity_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'applied_controls',
                'ordering': ['reference_control__control_id'],
            },
        ),
        migrations.CreateModel(
            name='ControlException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('technical', 'Technical Limitation'), ('business', 'Business Decision'), ('cost', 'Cost Constraint'), ('resource', 'Resource Limitation'), ('temporary', 'Temporary Exception'), ('compensating', 'Compensating Control in Place')], default='business', max_length=50)),
                ('reason', models.TextField(help_text='Why this exception is necessary')),
                ('compensating_controls', models.TextField(blank=True, help_text='Alternative controls in place')),
                ('risk_acceptance', models.TextField(blank=True, help_text='Documented risk acceptance')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='When this exception expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'control_exceptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_code', models.CharField(help_text='Unique code like UC-001, UC-002', max_length=100, unique=True)),
                ('control_name', models.CharField(max_length=500)),
                ('short_name', models.CharField(blank=True, max_length=200)),
                ('domain', models.CharField(db_index=True, help_text='e.g., Security Governance, Asset Management', max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('control_family', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('control_objective', models.TextField(blank=True)),
                ('implementation_guidance', models.TextField()),
                ('control_type', models.CharField(blank=True, choices=[('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective'), ('directive', 'Directive')], max_length=50)),
                ('automation_level', models.CharField(blank=True, choices=[('manual', 'Manual'), ('semi_automated', 'Semi-Automated'), ('automated', 'Automated')], max_length=50)),
                ('implementation_complexity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('estimated_effort_hours', models.IntegerField(blank=True, null=True)),
                ('maturity_level_1_criteria', models.TextField(blank=True, help_text='Level 1 - Initial/Ad-hoc')),
                ('maturity_level_2_criteria', models.TextField(blank=True, help_text='Level 2 - Managed')),
                ('maturity_level_3_criteria', models.TextField(blank=True, help_text='Level 3 - Defined')),
                ('maturity_level_4_criteria', models.TextField(blank=True, help_text='Level 4 - Quantitatively Managed')),
                ('maturity_level_5_criteria', models.TextField(blank=True, help_text='Level 5 - Optimizing')),
                ('testing_procedures', models.TextField(blank=True)),
                ('testing_frequency', models.CharField(blank=True, choices=[('continuous', 'Continuous'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=50)),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Array of prerequisite control codes')),
                ('related_controls', models.JSONField(blank=True, default=list, help_text='Array of related unified control IDs')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'unified_controls',
                'ordering': ['control_code'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedControlMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coverage_type', models.CharField(choices=[('full', 'Full Coverage'), ('partial', 'Partial Coverage'), ('supplemental', 'Supplemental')], default='full', max_length=50)),
                ('coverage_percentage', models.IntegerField(default=100, help_text='0-100 percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mapping_rationale', models.TextField(blank=True)),
                ('gap_description', models.TextField(blank=True)),
                ('supplemental_actions', models.TextField(blank=True)),
                ('confidence_score', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reference_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_mappings', to='library.referencecontrol')),
                ('unified_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_mappings', to='controls.unifiedcontrol')),
            ],
            options={
                'db_table': 'unified_control_mappings',
            },
        ),
    ]
