# Generated by Django 4.2.10 on 2026-02-16 18:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('implemented', 'Implemented'), ('testing', 'Testing'), ('operational', 'Operational'), ('needs_improvement', 'Needs Improvement'), ('non_compliant', 'Non-Compliant')], db_index=True, default='not_started', max_length=30)),
                ('implementation_notes', models.TextField(blank=True, help_text='Company-specific implementation details')),
                ('custom_procedures', models.TextField(blank=True, help_text='Company-specific procedures')),
                ('custom_frequency', models.CharField(blank=True, help_text='Override default frequency', max_length=50)),
                ('effectiveness_rating', models.IntegerField(blank=True, help_text='1=Ineffective, 5=Highly Effective', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_tested_date', models.DateField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('has_deficiencies', models.BooleanField(default=False)),
                ('deficiency_notes', models.TextField(blank=True)),
                ('remediation_plan', models.TextField(blank=True)),
                ('remediation_due_date', models.DateField(blank=True, null=True)),
                ('implementation_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost in company currency', max_digits=12, null=True)),
                ('annual_maintenance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'applied_controls',
                'ordering': ['reference_control__code'],
            },
        ),
        migrations.CreateModel(
            name='ControlException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_type', models.CharField(choices=[('technical', 'Technical Limitation'), ('business', 'Business Decision'), ('cost', 'Cost Constraint'), ('resource', 'Resource Limitation'), ('temporary', 'Temporary Exception'), ('compensating', 'Compensating Control in Place')], default='business', max_length=50)),
                ('reason', models.TextField(help_text='Why this exception is necessary')),
                ('compensating_controls', models.TextField(blank=True, help_text='Alternative controls in place')),
                ('risk_acceptance', models.TextField(blank=True, help_text='Documented risk acceptance')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='When this exception expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'control_exceptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(help_text='Unique control identifier (e.g., "AC-001", "IAM-002")', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed control description')),
                ('control_family', models.CharField(choices=[('access_control', 'Access Control'), ('asset_management', 'Asset Management'), ('cryptography', 'Cryptography'), ('physical_security', 'Physical Security'), ('operations_security', 'Operations Security'), ('communications_security', 'Communications Security'), ('system_acquisition', 'System Acquisition & Development'), ('supplier_relationships', 'Supplier Relationships'), ('incident_management', 'Incident Management'), ('business_continuity', 'Business Continuity'), ('compliance', 'Compliance'), ('risk_management', 'Risk Management'), ('human_resources', 'Human Resources Security'), ('information_security', 'Information Security')], default='access_control', max_length=100)),
                ('control_type', models.CharField(choices=[('preventive', 'Preventive'), ('detective', 'Detective'), ('corrective', 'Corrective'), ('deterrent', 'Deterrent'), ('compensating', 'Compensating')], default='preventive', max_length=50)),
                ('implementation_guidance', models.TextField(blank=True, help_text='How to implement this control')),
                ('testing_procedures', models.TextField(blank=True, help_text='How to test control effectiveness')),
                ('automation_level', models.CharField(choices=[('manual', 'Manual'), ('semi_automated', 'Semi-Automated'), ('automated', 'Fully Automated')], default='manual', max_length=20)),
                ('frequency', models.CharField(choices=[('continuous', 'Continuous'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('ad_hoc', 'Ad-Hoc')], default='monthly', help_text='Recommended testing/review frequency', max_length=50)),
                ('maturity_level', models.IntegerField(default=1, help_text='1=Initial, 2=Managed, 3=Defined, 4=Quantitatively Managed, 5=Optimizing', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('implementation_complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('estimated_effort_hours', models.IntegerField(blank=True, help_text='Estimated hours to implement', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this control is available to companies')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization (e.g., ["cloud", "AWS", "encryption"])')),
            ],
            options={
                'db_table': 'reference_controls',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RequirementReferenceControl',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_rationale', models.TextField(blank=True, help_text='Why this control satisfies this requirement')),
                ('coverage_level', models.CharField(choices=[('full', 'Full Coverage'), ('partial', 'Partial Coverage'), ('supporting', 'Supporting Control')], default='full', help_text='How well this control satisfies the requirement', max_length=20)),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this is a primary control for the requirement')),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('reference_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_mappings', to='controls.referencecontrol')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_mappings', to='library.requirement')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requirement_reference_controls',
                'ordering': ['requirement__code', 'reference_control__code'],
            },
        ),
        migrations.AddIndex(
            model_name='referencecontrol',
            index=models.Index(fields=['code'], name='reference_c_code_e04cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='referencecontrol',
            index=models.Index(fields=['control_family', 'is_published'], name='reference_c_control_9d4dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='referencecontrol',
            index=models.Index(fields=['priority', 'control_type'], name='reference_c_priorit_1536b8_idx'),
        ),
        migrations.AddField(
            model_name='controlexception',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlexception',
            name='applied_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='controls.appliedcontrol'),
        ),
        migrations.AddField(
            model_name='controlexception',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='control_owner',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_controls', to=settings.AUTH_USER_MODEL),
        ),
    ]
