# Generated by Django 4.2.10 on 2026-02-16 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controls', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedcontrol',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this control (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_controls', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='last_tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='reference_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_instances', to='controls.referencecontrol'),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='requirementreferencecontrol',
            index=models.Index(fields=['requirement', 'coverage_level'], name='requirement_require_a83e93_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementreferencecontrol',
            index=models.Index(fields=['reference_control', 'is_primary'], name='requirement_referen_0ed7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementreferencecontrol',
            index=models.Index(fields=['validation_status'], name='requirement_validat_89f959_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementreferencecontrol',
            unique_together={('requirement', 'reference_control')},
        ),
        migrations.AddIndex(
            model_name='controlexception',
            index=models.Index(fields=['company', 'is_active'], name='control_exc_company_e1df37_idx'),
        ),
        migrations.AddIndex(
            model_name='controlexception',
            index=models.Index(fields=['applied_control', 'is_active'], name='control_exc_applied_c38bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='controlexception',
            index=models.Index(fields=['expiration_date'], name='control_exc_expirat_eef97a_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['company', 'status'], name='applied_con_company_16bba7_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['company', 'department'], name='applied_con_company_8b2e58_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['control_owner', 'status'], name='applied_con_control_2a775a_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['next_review_date'], name='applied_con_next_re_e08216_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['has_deficiencies'], name='applied_con_has_def_80e0b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appliedcontrol',
            unique_together={('company', 'reference_control', 'department')},
        ),
    ]
