# Generated by Django 4.2.10 on 2026-03-17 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('core', '0001_initial'),
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcontrolmapping',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedcontrol',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unified_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unifiedcontrol',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_unified_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlexception',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlexception',
            name='applied_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='controls.appliedcontrol'),
        ),
        migrations.AddField(
            model_name='controlexception',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company'),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='control_owner',
            field=models.ForeignKey(blank=True, help_text='Person responsible for this control', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this control (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_controls', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='last_tested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='reference_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_controls', to='library.referencecontrol'),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appliedcontrol',
            name='unified_control',
            field=models.ForeignKey(blank=True, help_text='Link to unified control (new unified model)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_instances', to='controls.unifiedcontrol'),
        ),
        migrations.AddIndex(
            model_name='unifiedcontrolmapping',
            index=models.Index(fields=['coverage_type'], name='ucmap_covtype_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedcontrolmapping',
            unique_together={('reference_control', 'unified_control')},
        ),
        migrations.AddIndex(
            model_name='unifiedcontrol',
            index=models.Index(fields=['control_code'], name='unified_code_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedcontrol',
            index=models.Index(fields=['domain'], name='unified_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedcontrol',
            index=models.Index(fields=['is_active'], name='unified_active_idx'),
        ),
        migrations.AddIndex(
            model_name='controlexception',
            index=models.Index(fields=['company', 'is_active'], name='exception_company_active_idx'),
        ),
        migrations.AddIndex(
            model_name='controlexception',
            index=models.Index(fields=['applied_control', 'is_active'], name='exception_control_active_idx'),
        ),
        migrations.AddIndex(
            model_name='controlexception',
            index=models.Index(fields=['expiration_date'], name='exception_expiration_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['company', 'status'], name='applied_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['company', 'department'], name='applied_company_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['control_owner', 'status'], name='applied_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['next_review_date'], name='applied_review_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrol',
            index=models.Index(fields=['has_deficiencies'], name='applied_def_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appliedcontrol',
            unique_together={('company', 'reference_control', 'department')},
        ),
    ]
