# Generated by Django 4.2.10 on 2026-03-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_initial'),
        ('controls', '0004_add_performance_indexes'),
    ]

    operations = [
    ]
