# Generated by Django 4.2.10 on 2026-03-10 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_merge_0002_initial_0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appliedcontrol',
            name='idx_applied_maturity_status',
        ),
        migrations.RenameIndex(
            model_name='appliedcontrol',
            new_name='applied_company_status_idx',
            old_name='applied_con_company_16bba7_idx',
        ),
        migrations.RenameIndex(
            model_name='appliedcontrol',
            new_name='applied_company_dept_idx',
            old_name='applied_con_company_8b2e58_idx',
        ),
        migrations.RenameIndex(
            model_name='appliedcontrol',
            new_name='applied_owner_status_idx',
            old_name='applied_con_control_2a775a_idx',
        ),
        migrations.RenameIndex(
            model_name='appliedcontrol',
            new_name='applied_review_idx',
            old_name='applied_con_next_re_e08216_idx',
        ),
        migrations.RenameIndex(
            model_name='appliedcontrol',
            new_name='applied_def_idx',
            old_name='applied_con_has_def_80e0b9_idx',
        ),
        migrations.RenameIndex(
            model_name='controlexception',
            new_name='exception_company_active_idx',
            old_name='control_exc_company_e1df37_idx',
        ),
        migrations.RenameIndex(
            model_name='controlexception',
            new_name='exception_control_active_idx',
            old_name='control_exc_applied_c38bcb_idx',
        ),
        migrations.RenameIndex(
            model_name='controlexception',
            new_name='exception_expiration_idx',
            old_name='control_exc_expirat_eef97a_idx',
        ),
        migrations.RenameIndex(
            model_name='referencecontrol',
            new_name='refctrl_code_idx',
            old_name='reference_c_code_e04cbc_idx',
        ),
        migrations.RenameIndex(
            model_name='referencecontrol',
            new_name='refctrl_family_pub_idx',
            old_name='reference_c_control_9d4dc8_idx',
        ),
        migrations.RenameIndex(
            model_name='referencecontrol',
            new_name='refctrl_priority_type_idx',
            old_name='reference_c_priorit_1536b8_idx',
        ),
        migrations.RenameIndex(
            model_name='requirementreferencecontrol',
            new_name='reqctrl_req_cov_idx',
            old_name='requirement_require_a83e93_idx',
        ),
        migrations.RenameIndex(
            model_name='requirementreferencecontrol',
            new_name='reqctrl_ctrl_primary_idx',
            old_name='requirement_referen_0ed7fb_idx',
        ),
        migrations.RenameIndex(
            model_name='requirementreferencecontrol',
            new_name='reqctrl_validation_idx',
            old_name='requirement_validat_89f959_idx',
        ),
        migrations.RenameIndex(
            model_name='unifiedcontrol',
            new_name='unified_code_idx',
            old_name='uc_code_idx',
        ),
        migrations.RenameIndex(
            model_name='unifiedcontrol',
            new_name='unified_domain_idx',
            old_name='uc_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='unifiedcontrol',
            new_name='unified_active_idx',
            old_name='uc_active_idx',
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='maturity_assessment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='maturity_level',
            field=models.IntegerField(choices=[(1, 'Level 1 - Initial/Ad-hoc'), (2, 'Level 2 - Managed'), (3, 'Level 3 - Defined'), (4, 'Level 4 - Quantitatively Managed'), (5, 'Level 5 - Optimizing')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='maturity_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='maturity_target_level',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3),
        ),
        migrations.AlterField(
            model_name='appliedcontrol',
            name='unified_control',
            field=models.ForeignKey(blank=True, help_text='Link to unified control (new unified model)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_instances', to='controls.unifiedcontrol'),
        ),
        migrations.AlterField(
            model_name='unifiedcontrol',
            name='control_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='unifiedcontrol',
            name='control_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unifiedcontrol',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unifiedcontrol',
            name='domain',
            field=models.CharField(db_index=True, help_text='e.g., Security Governance, Asset Management', max_length=200),
        ),
        migrations.AlterField(
            model_name='unifiedcontrol',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unifiedcontrol',
            name='implementation_guidance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unifiedcontrolmapping',
            name='confidence_score',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='unifiedcontrolmapping',
            name='coverage_percentage',
            field=models.IntegerField(default=100, help_text='0-100 percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='unifiedcontrolmapping',
            name='coverage_type',
            field=models.CharField(choices=[('full', 'Full Coverage'), ('partial', 'Partial Coverage'), ('supplemental', 'Supplemental')], default='full', max_length=50),
        ),
        migrations.AlterField(
            model_name='unifiedcontrolmapping',
            name='gap_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unifiedcontrolmapping',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unifiedcontrolmapping',
            name='mapping_rationale',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='unifiedcontrolmapping',
            name='supplemental_actions',
            field=models.TextField(blank=True),
        ),
    ]
