# Generated by Django 4.2.10 on 2026-02-16 18:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import evidence.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('controls', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Evidence name/title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Evidence description')),
                ('file', models.FileField(max_length=500, upload_to=evidence.models.evidence_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'zip', '7z', 'tar', 'gz', 'json', 'xml', 'yaml', 'log', 'md'])])),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for integrity verification', max_length=64)),
                ('evidence_type', models.CharField(choices=[('policy', 'Policy Document'), ('procedure', 'Procedure'), ('screenshot', 'Screenshot'), ('report', 'Report'), ('log', 'Log File'), ('certificate', 'Certificate'), ('configuration', 'Configuration File'), ('scan_result', 'Scan Result'), ('audit_report', 'Audit Report'), ('training_record', 'Training Record'), ('other', 'Other')], default='other', max_length=50)),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this evidence is still valid')),
                ('validity_start_date', models.DateField(blank=True, help_text='When this evidence becomes valid', null=True)),
                ('validity_end_date', models.DateField(blank=True, help_text='When this evidence expires', null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_update', 'Needs Update')], db_index=True, default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='Restrict access to specific roles')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization and search')),
                ('version', models.CharField(default='1.0', help_text='Evidence version', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='evidence.evidence')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evidence',
                'db_table': 'evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppliedControlEvidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('implementation', 'Implementation Evidence'), ('testing', 'Testing Evidence'), ('monitoring', 'Monitoring Evidence'), ('documentation', 'Documentation'), ('audit', 'Audit Evidence')], default='implementation', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes about how this evidence supports the control')),
                ('relevance_score', models.IntegerField(default=5, help_text='How relevant this evidence is (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('applied_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='controls.appliedcontrol')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_links', to='evidence.evidence')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applied_control_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_comments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='evidence.evidence')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='evidence.evidencecomment')),
            ],
            options={
                'db_table': 'evidence_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['evidence', '-created_at'], name='evidence_co_evidenc_e3f9b8_idx'), models.Index(fields=['company', '-created_at'], name='evidence_co_company_fd475c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAccessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_type', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('preview', 'Previewed')], default='view', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_accesses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.company')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='evidence.evidence')),
            ],
            options={
                'db_table': 'evidence_access_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['evidence', '-created_at'], name='evidence_ac_evidenc_ae04bb_idx'), models.Index(fields=['accessed_by', '-created_at'], name='evidence_ac_accesse_a0a3c6_idx'), models.Index(fields=['company', '-created_at'], name='evidence_ac_company_21b777_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['company', 'evidence_type'], name='evidence_company_6c1f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['company', 'verification_status'], name='evidence_company_10857c_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['company', 'uploaded_by'], name='evidence_company_fcd37b_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['validity_end_date'], name='evidence_validit_a42b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['is_valid', 'verification_status'], name='evidence_is_vali_8ae8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrolevidence',
            index=models.Index(fields=['company', 'applied_control'], name='applied_con_company_10d502_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrolevidence',
            index=models.Index(fields=['company', 'evidence'], name='applied_con_company_588e86_idx'),
        ),
        migrations.AddIndex(
            model_name='appliedcontrolevidence',
            index=models.Index(fields=['link_type'], name='applied_con_link_ty_880a10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appliedcontrolevidence',
            unique_together={('applied_control', 'evidence')},
        ),
    ]
