# Generated by Django 4.2.10 on 2026-03-09 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, help_text='Snapshot of email at time of action (preserved if user deleted)', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(choices=[('control_applied', 'Control Applied'), ('control_updated', 'Control Updated'), ('control_deleted', 'Control Deleted'), ('control_status_changed', 'Control Status Changed'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_updated', 'Evidence Updated'), ('evidence_deleted', 'Evidence Deleted'), ('evidence_approved', 'Evidence Approved'), ('evidence_rejected', 'Evidence Rejected'), ('evidence_downloaded', 'Evidence Downloaded'), ('evidence_linked', 'Evidence Linked to Control'), ('evidence_unlinked', 'Evidence Unlinked from Control'), ('risk_created', 'Risk Created'), ('risk_updated', 'Risk Updated'), ('risk_deleted', 'Risk Deleted'), ('risk_status_changed', 'Risk Status Changed'), ('risk_assessed', 'Risk Assessed'), ('compliance_calculated', 'Compliance Calculated'), ('framework_adopted', 'Framework Adopted'), ('framework_certified', 'Framework Certified'), ('member_invited', 'Member Invited'), ('member_joined', 'Member Joined'), ('member_role_changed', 'Member Role Changed'), ('member_removed', 'Member Removed'), ('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], db_index=True, max_length=60)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=36)),
                ('object_repr', models.CharField(blank=True, help_text='str() of the object at time of action', max_length=500)),
                ('resource_type', models.CharField(blank=True, db_index=True, help_text='e.g. "AppliedControl", "Evidence", "Risk"', max_length=100)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": ["old_value", "new_value"]} for updates; full data for creates')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context: framework codes, link types, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
