# Generated by Django 4.2.10 on 2026-03-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_company_03f3f6_idx',
            old_name='audit_logs_company_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_company_86928e_idx',
            old_name='audit_logs_company_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_company_dac151_idx',
            old_name='audit_logs_company_res_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_actor_i_9ecce2_idx',
            old_name='audit_logs_actor_ts_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='{"field": ["old_value", "new_value"]} for updates; full data for creates'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra context: framework codes, link types, etc.'),
        ),
    ]
