# Generated by Django 4.2.10 on 2026-03-06 11:32

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import secrets
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=core.models._default_reset_expiry)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='invitations_token_5b330c_idx',
            old_name='invitations_token_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='invitations_company_38e4da_idx',
            old_name='invitations_company_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User-level notification and appearance preferences. Shape: {email_notifications, desktop_notifications, compliance_alerts, risk_alerts, evidence_reminders, theme, language}'),
        ),
        migrations.AlterField(
            model_name='company',
            name='max_storage_mb',
            field=models.IntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=core.models._default_invite_expiry),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='password_re_token_060a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', '-created_at'], name='password_re_user_id_fcb0eb_idx'),
        ),
    ]
