# Generated by Django 4.2.10 on 2026-03-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordresettoken_and_more'),
        ('core', '0005_userpref'),
    ]

    operations = [
    ]
